name: Build and Release APK

on:
  push:
    branches:
      - main  # O workflow será acionado ao fazer push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo para fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo para configurar o JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Passo para cache de dependências do Gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Adicionar permissão de execução ao gradlew
      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      # Passo para decodificar o keystore base64
      - name: Set up Keystore
        run: |
          mkdir -p app/keystore  # Criar o diretório onde o keystore será colocado
          echo "$KEYSTORE_FILE" | base64 --decode > app/keystore/prismakeystore.jks  # Decodificar e salvar o keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}  # O segredo base64 do keystore

      # Passo para compilar o APK (assembleRelease)
      - name: Build APK
        run: ./gradlew assembleRelease

      # Passo para assinar o APK
      - name: Sign APK
        run: |
          # Confirme que o caminho para o keystore está correto
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore app/keystore/prismakeystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk key0prisma

      # Passo para criar a release no GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}  # Definindo o nome da tag da release
          release_name: "Release v${{ github.run_number }}"
          draft: false
          prerelease: false

      # Passo para fazer upload do APK para a release
      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk  # Caminho correto para o APK
          asset_name: app-release.apk  # Nome do arquivo
          asset_content_type: application/vnd.android.package-archive
