name: Build and Release APK

on:
  push:
    branches:
      - main # Ação será acionada em pushes na branch main

permissions:
  contents: write # Garante permissões básicas para o GITHUB_TOKEN (não usado aqui)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17 # Java 17 necessário para o Android Gradle Plugin
          distribution: 'temurin'

      # Conceder permissão de execução ao Gradle Wrapper
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # Cache do Gradle para acelerar builds futuros
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build do APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Criar uma release no GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Usar o token pessoal aqui
        with:
          tag_name: ${{ github.ref_name }} # Nome da tag que acionou o workflow
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      # Fazer upload do APK para a release
      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Usar o token pessoal aqui
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
